name: Yarn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  yarn-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Test that dist folder is removed
        run: yarn clean

      - name: Test that it installs dependencies from yarn.lock
        run: yarn ci

      - name: Test that it compiles and updates dist folder
        run: yarn build

      - name: Test that linter passes
        run: yarn lint
